# Distributed under the MIT License.
# See LICENSE.txt for details.

import inspect
import logging
import os
import re
import shutil
import stat
import subprocess
import unittest
from pathlib import Path

import yaml

from spectre.Informer import unit_test_build_path, unit_test_src_path
from spectre.support.BinDirectory import (
    PYTHON_DIR_NAME,
    SUPPORT_FILES,
    BinDirectory,
    _check_build_is_relocatable,
)
from spectre.support.DirectoryStructure import PipelineStep, Segment
from spectre.support.Logging import configure_logging
from spectre.support.Machines import this_machine


class TestBinDirectory(unittest.TestCase):
    def setUp(self):
        self.test_dir = Path(unit_test_build_path(), "BinDirectory").resolve()
        # Start from a clean directory. A bin directory left behind by an
        # interrupted run would be reused instead of created, which changes
        # what these tests exercise.
        shutil.rmtree(self.test_dir, ignore_errors=True)
        self.test_dir.mkdir(parents=True)
        self.build_dir = Path(unit_test_build_path()).parent.parent
        self.build_bin_dir = self.build_dir / "bin"
        self.build_lib_dir = self.build_dir / "lib"
        # The source tree. A scheduled run must not reference it, or the build
        # directory's 'bin', once it has a bin directory of its own.
        self.source_dir = Path(unit_test_src_path()).parent.parent

        # Create an executable that just outputs all arguments passed to it
        self.executable = self.test_dir / "TestExec"
        self.executable.write_text("""#!/bin/bash
echo $@ > out.txt
""")
        self.executable.chmod(self.executable.stat().st_mode | stat.S_IEXEC)

        # Create an input file
        self.input_file = self.test_dir / "InputFile.yaml"
        self.input_file.write_text("""
Executable: TestExec
MetadataOption: {{ metadata_option }}
---
Option: {{ extra_option }}
""")

        # A stand-in installation, laid out like a build directory. The tests
        # drive its CLI as a subprocess, so the code under test self-locates
        # here: it finds the support files that a machine build would have
        # configured, and a CMake cache that says the build is relocatable.
        # A test build usually has neither.
        self.installation = BinDirectory(self.test_dir / "Installation/bin")
        self.installation.path.mkdir(parents=True)
        shutil.copy(
            self.build_bin_dir / "spectre", self.installation.spectre_cli
        )
        # Link rather than copy the Python package: 'create' dereferences it,
        # so a simulation still gets a real copy, but this costs nothing
        self.installation.python_dir.symlink_to(
            self.build_bin_dir / PYTHON_DIR_NAME
        )
        (self.installation.path.parent / "CMakeCache.txt").write_text(
            "BUILD_SHARED_LIBS:BOOL=OFF\n"
        )
        self.installation.support_dir.mkdir()
        (self.installation.support_dir / "SubmitTemplateBase.sh").write_text(
            """\
SPECTRE_EXECUTABLE={{ executable }}
SPECTRE_CLI={{ spectre_cli }}
{% block derived %}
{% endblock %}
"""
        )
        (self.installation.support_dir / "SubmitTemplate.sh").write_text("""\
{% extends "SubmitTemplateBase.sh" %}
{% block derived %}
NUM_NODES={{ num_nodes | default(1) }}
{% endblock %}
""")
        # Empty launch commands, so a directly executed run runs the
        # executable itself
        with open(
            self.installation.support_dir / "Machine.yaml", "w"
        ) as open_machinefile:
            yaml.safe_dump(
                dict(
                    Machine=dict(
                        Name="TestMachine",
                        Description="Just for testing",
                        DefaultTasksPerNode=2,
                        DefaultProcsPerTask=3,
                        DefaultQueue="production",
                        DefaultTimeLimit="1-00:00:00",
                        LaunchCommandSingleNode=[],
                        LaunchCommandLoginNode=[],
                    )
                ),
                open_machinefile,
            )
        # CMake generates these next to the support files, for its own use.
        # They hold absolute build-directory paths, so a simulation must never
        # get them.
        self.cmake_generated = ["CTestTestfile.cmake", "cmake_install.cmake"]
        for file_name in self.cmake_generated:
            (self.installation.support_dir / file_name).write_text(
                f"# generated by cmake in {self.installation.path.parent}\n"
            )

    def tearDown(self):
        shutil.rmtree(self.test_dir, ignore_errors=True)

    def run_cli(self, *args, cli=None, path_prefix=None):
        """Run a SpECTRE CLI as a subprocess

        The environment holds nothing of the build directory, so the CLI has to
        find everything through its own location. Runs the stand-in
        installation's CLI unless another one is given.
        """
        path = "/usr/bin:/bin"
        if path_prefix:
            path = f"{path_prefix}:{path}"
        result = subprocess.run(
            [str(cli or self.installation.spectre_cli), *args],
            capture_output=True,
            text=True,
            env={"PATH": path, "HOME": os.environ.get("HOME", "/tmp")},
        )
        self.assertEqual(result.returncode, 0, msg=result.stderr[-3000:])
        return result

    def schedule_cli(self, *args, **kwargs):
        """Run 'spectre schedule' for the test executable and input file"""
        return self.run_cli(
            "schedule",
            str(self.input_file),
            "--executable",
            str(self.executable),
            "--scheduler",
            "echo",
            "--no-validate",
            "--submit",
            "-p",
            "extra_option=TestOpt",
            "-p",
            "metadata_option=MetaOpt",
            *args,
            **kwargs,
        )

    def resolved_sys_path(self, directory=None):
        """The 'sys.path' entries that the CLI wrapper puts Python on

        Runs the 'python-spectre' wrapper, which passes its arguments straight
        to the interpreter. With a 'directory', copies the wrapper there first
        and creates a package directory next to it, to check what the same
        script does elsewhere.
        """
        wrapper = self.build_bin_dir / "python-spectre"
        if directory is not None:
            directory.mkdir(parents=True, exist_ok=True)
            (directory / PYTHON_DIR_NAME).mkdir(exist_ok=True)
            wrapper = directory / "python-spectre"
            shutil.copy(self.build_bin_dir / "python-spectre", wrapper)
        printed = subprocess.run(
            [str(wrapper), "-c", "import sys; print('\\n'.join(sys.path))"],
            capture_output=True,
            text=True,
            check=True,
        )
        # 'sys.path[0]' is the working directory for '-c'
        return printed.stdout.splitlines()[1:]

    def assert_independent_of_build_dir(self, path):
        """Assert that nothing in the file at 'path' points into the build

        The whole point of the bin directory is that a scheduled job doesn't
        reach back into the build directory or the source tree, so it keeps
        working when they are recompiled, moved or deleted.
        """
        text = Path(path).read_text()
        self.assertNotIn(str(self.build_bin_dir), text, msg=f"in {path}")
        self.assertNotIn(str(self.build_lib_dir), text, msg=f"in {path}")
        # Build directories usually sit inside the source tree, and then the
        # simulation these tests create has the source path as a prefix too.
        # Only source paths outside the build directory are a reach-back.
        for source_path in re.findall(
            re.escape(str(self.source_dir)) + r"[^\s\"\']*", text
        ):
            self.assertTrue(
                source_path.startswith(str(self.build_dir)),
                msg=f"'{source_path}' in {path}",
            )

    def test_bin_directory(self):
        segments_dir = self.test_dir / "Segments"
        bin_dir = BinDirectory(segments_dir / "bin")

        # Schedule the first segment through the stand-in installation's CLI.
        # This creates the bin directory.
        self.schedule_cli("--segments-dir", str(segments_dir))

        # The bin directory holds what the job needs after submission, and the
        # support files are next to it. Nothing else is: the files CMake
        # generates next to the build directory's support files hold absolute
        # build paths, and must not travel.
        for expected in ["TestExec", "spectre", "python/spectre/support"]:
            self.assertTrue(
                (bin_dir.path / expected).exists(), msg=f"missing: {expected}"
            )
        self.assertEqual(
            sorted(path.name for path in bin_dir.support_dir.iterdir()),
            sorted(SUPPORT_FILES),
        )
        # The machine file is looked up relative to the running installation,
        # so a job reads the simulation's copy
        self.assertEqual(
            inspect.signature(this_machine)
            .parameters["machinefile_path"]
            .default,
            BinDirectory.this().support_dir / "Machine.yaml",
        )

        # Nothing the job reads points back into the build or the source
        segment_0 = segments_dir / "Segment_0000"
        self.assert_independent_of_build_dir(segment_0 / "Submit.sh")
        self.assert_independent_of_build_dir(
            segment_0 / "SchedulerContext.yaml"
        )
        with open(segment_0 / "SchedulerContext.yaml", "r") as open_context:
            context = yaml.safe_load(open_context)
        self.assertEqual(context["bin_dir"], str(bin_dir.path))
        self.assertEqual(context["executable"], str(bin_dir.path / "TestExec"))
        self.assertEqual(context["spectre_cli"], str(bin_dir.spectre_cli))
        self.assertEqual(
            context["submit_script_template"],
            str(bin_dir.support_dir / "SubmitTemplate.sh"),
        )
        self.assertTrue(context["create_bin"])

        # A rebuilt executable of the same name, first on the 'PATH', does not
        # displace the frozen one: the simulation runs one binary throughout.
        # Scheduling again also reuses the bin directory rather than copying
        # the build directory over it.
        rebuilt = self.test_dir / "Rebuilt/TestExec"
        rebuilt.parent.mkdir()
        rebuilt.write_text("#!/bin/bash\n# rebuilt\n")
        rebuilt.chmod(rebuilt.stat().st_mode | stat.S_IEXEC)
        created_at = bin_dir.spectre_cli.stat().st_mtime_ns
        (segment_0 / "Checkpoints/Checkpoint_0000").mkdir(parents=True)
        self.run_cli(
            "resubmit",
            str(segments_dir),
            "--submit",
            path_prefix=rebuilt.parent,
        )
        segment_1 = segments_dir / "Segment_0001"
        self.assertTrue((segment_1 / "Submit.sh").is_file())
        self.assertEqual(bin_dir.spectre_cli.stat().st_mtime_ns, created_at)
        self.assertNotIn("rebuilt", (bin_dir.path / "TestExec").read_text())
        self.assert_independent_of_build_dir(segment_1 / "Submit.sh")

        # The simulation's own CLI schedules the next segment. That exercises
        # the copied Python package, the relocatable wrapper, and resolving an
        # executable that the environment does not have.
        (segment_1 / "Checkpoints/Checkpoint_0000").mkdir(parents=True)
        self.run_cli(
            "resubmit",
            str(segments_dir),
            "--submit",
            cli=bin_dir.spectre_cli,
        )
        segment_2 = segments_dir / "Segment_0002"
        self.assert_independent_of_build_dir(segment_2 / "Submit.sh")
        self.assertIn(
            str(bin_dir.path / "TestExec"),
            (segment_2 / "Submit.sh").read_text(),
        )

        # A directly executed run is not continued, so it gets no bin
        # directory by default, but '--create-bin' still creates one
        direct_dir = self.test_dir / "Direct"
        self.schedule_cli("--run-dir", str(direct_dir), "--no-schedule")
        self.assertFalse((direct_dir / "bin").exists())
        asked_for_one = self.test_dir / "AskedForOne"
        self.schedule_cli(
            "--run-dir", str(asked_for_one), "--no-schedule", "--create-bin"
        )
        self.assertTrue(
            BinDirectory(asked_for_one / "bin").spectre_cli.is_file()
        )

    def test_bin_directory_search(self):
        # Which bin directory a run uses is decided by 'find'. Everything here
        # is planted: this is about the walk, not about what gets copied.
        def a_bin_dir(path):
            bin_dir = BinDirectory(path / "bin")
            bin_dir.path.mkdir(parents=True)
            bin_dir.spectre_cli.touch()
            return bin_dir

        # A run tree that happens to sit below an unrelated simulation does not
        # pick up that simulation's bin directory: the walk stops at the first
        # directory the scheduler didn't create.
        a_bin_dir(self.test_dir / "Decoy")
        unrelated_dir = self.test_dir / "Decoy/NotASimulationDir"
        segment_dir = Segment.first(
            PipelineStep.first(unrelated_dir, label="Lev2").path
        ).path
        segment_dir.mkdir(parents=True)
        self.assertIsNone(BinDirectory.find(segment_dir))

        # Its own simulation root is found. A build directory's 'bin' is a hit
        # like any other, so a run tree inside one runs from it.
        own_bin_dir = a_bin_dir(unrelated_dir)
        self.assertEqual(BinDirectory.find(segment_dir).path, own_bin_dir.path)
        (unrelated_dir / "CMakeCache.txt").touch()
        self.assertEqual(BinDirectory.find(segment_dir).path, own_bin_dir.path)

        # Steps of a pipeline share the bin directory at its root, unless a
        # step has one of its own: the nearest wins.
        pipeline_dir = self.test_dir / "Pipeline"
        shared_bin_dir = a_bin_dir(pipeline_dir)
        step_dir = PipelineStep.first(pipeline_dir, label="Inspiral").path
        step_segment_dir = Segment.first(step_dir).path
        step_segment_dir.mkdir(parents=True)
        self.assertEqual(
            BinDirectory.find(step_segment_dir).path, shared_bin_dir.path
        )
        nearer_bin_dir = a_bin_dir(step_dir)
        self.assertEqual(
            BinDirectory.find(step_segment_dir).path, nearer_bin_dir.path
        )

    def test_relocatable_build_guard(self):
        # Executables of a build with shared SpECTRE libraries load them out of
        # it, so copying them would give a false sense of safety. The build's
        # own CMake cache says which kind of build it is, because library file
        # names differ between systems.
        build_dir = self.test_dir / "SharedLibsBuild"
        build_dir.mkdir()
        cache_file = build_dir / "CMakeCache.txt"
        # A directory that was never configured is not a build directory
        _check_build_is_relocatable(build_dir)
        cache_file.write_text("BUILD_SHARED_LIBS:BOOL=ON\n")
        with self.assertRaises(RuntimeError):
            _check_build_is_relocatable(build_dir)
        cache_file.write_text("BUILD_SHARED_LIBS:BOOL=OFF\n")
        _check_build_is_relocatable(build_dir)

    def test_cli_finds_the_package_next_to_itself(self):
        # The wrapper reaches the Python package through its own location, so
        # a copy of it in a simulation's bin directory uses the package next to
        # the copy. The entries configured into it at build time follow, so the
        # package next to the wrapper wins.
        build_entries = self.resolved_sys_path()
        self.assertEqual(
            build_entries[0], str(self.build_bin_dir / PYTHON_DIR_NAME)
        )

        copied_dir = self.test_dir / "CopiedBin"
        copied_entries = self.resolved_sys_path(copied_dir)
        self.assertEqual(copied_entries[0], str(copied_dir / PYTHON_DIR_NAME))
        # Everything after the first entry is baked in at build time. In the
        # build directory the baked package entry duplicates the first and
        # Python drops it; in a copy it stays, followed by the same tail
        self.assertEqual(
            copied_entries[1:],
            [str(self.build_bin_dir / PYTHON_DIR_NAME)] + build_entries[1:],
        )

        # The canonical 'PYTHONPATH' that CMake hands to tests and to
        # 'LoadPython.sh' starts with the same package directory
        canonical = re.search(
            r"^export PYTHONPATH=(.*)$",
            (self.build_bin_dir / "LoadPython.sh").read_text(),
            re.MULTILINE,
        ).group(1)
        self.assertEqual(
            canonical.split(":")[0],
            str(self.build_bin_dir / PYTHON_DIR_NAME),
        )


if __name__ == "__main__":
    configure_logging(log_level=logging.DEBUG)
    unittest.main(verbosity=2)
