var searchData=
[
  ['jacobian_2663',['Jacobian',['../structdomain_1_1Tags_1_1Jacobian.html',1,'domain::Tags::Jacobian&lt; Dim, SourceFrame, TargetFrame &gt;'],['../structStrahlkorperTags_1_1Jacobian.html',1,'StrahlkorperTags::Jacobian&lt; Frame &gt;'],['../classdomain_1_1CoordinateMapBase.html#a8b81d3f89a329f64ec8ed4ca8ee4ddaa',1,'domain::CoordinateMapBase::jacobian(tnsr::I&lt; double, Dim, SourceFrame &gt; source_point, double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt;{}) const noexcept=0'],['../classdomain_1_1CoordinateMapBase.html#a02c83082eeeb29d112951611afdd05bc',1,'domain::CoordinateMapBase::jacobian(tnsr::I&lt; DataVector, Dim, SourceFrame &gt; source_point, double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt;{}) const noexcept=0'],['../classdomain_1_1CoordinateMap.html#a7f8d625845fda99dee4cb2e2251b9e48',1,'domain::CoordinateMap::jacobian(tnsr::I&lt; double, dim, SourceFrame &gt; source_point, const double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt;{}) const noexcept override'],['../classdomain_1_1CoordinateMap.html#af0efd0b58d08b5cd18cfde5a960715c6',1,'domain::CoordinateMap::jacobian(tnsr::I&lt; DataVector, dim, SourceFrame &gt; source_point, const double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt;&gt;{}) const noexcept override'],['../structCce_1_1Solutions_1_1SphericalMetricData.html#a57125f7385d1891b5366bba68761083e',1,'Cce::Solutions::SphericalMetricData::jacobian()']]],
  ['jacobian_5fis_5ftime_5fdependent_2664',['jacobian_is_time_dependent',['../classdomain_1_1CoordinateMapBase.html#af7e1ed182ad9ce3825ce22a87d9cf0e9',1,'domain::CoordinateMapBase::jacobian_is_time_dependent()'],['../classdomain_1_1CoordinateMap.html#a333317b7bd25cf5213fc57ea70fc7666',1,'domain::CoordinateMap::jacobian_is_time_dependent()']]],
  ['jacobiancompute_2665',['JacobianCompute',['../structdomain_1_1Tags_1_1JacobianCompute.html',1,'domain::Tags::JacobianCompute&lt; Dim, SourceFrame, TargetFrame &gt;'],['../structStrahlkorperTags_1_1JacobianCompute.html',1,'StrahlkorperTags::JacobianCompute&lt; Frame &gt;']]],
  ['jacobipreconditioner_2666',['JacobiPreconditioner',['../structTestHelpers_1_1LinearSolver_1_1JacobiPreconditioner.html',1,'TestHelpers::LinearSolver']]],
  ['jbarqminus2ethbeta_2667',['JbarQMinus2EthBeta',['../structCce_1_1Tags_1_1JbarQMinus2EthBeta.html',1,'Cce::Tags']]],
  ['jmp_5fbuf_2668',['jmp_buf',['http://en.cppreference.com/w/cpp/utility/program/jmp_buf.html',1,'std']]],
  ['join_2669',['join',['http://en.cppreference.com/w/cpp/thread/thread/join.html',1,'std::thread::join()'],['../group__ComputationalDomainGroup.html#gga6874579f1400ff7d0d77cbfa978289e2aa286d9991c6a547ae25a5f5216164b8f',1,'amr::Join()']]],
  ['joinable_2670',['joinable',['http://en.cppreference.com/w/cpp/thread/thread/joinable.html',1,'std::thread']]],
  ['jumpposition_2671',['JumpPosition',['../structNewtonianEuler_1_1AnalyticData_1_1ShuOsherTube_1_1JumpPosition.html',1,'NewtonianEuler::AnalyticData::ShuOsherTube']]]
];
