var searchData=
[
  ['h5_1973',['h5',['../namespaceh5.html',1,'']]],
  ['h5_5ftype_1974',['h5_type',['../group__HDF5Group.html#ga2207323f530e6e11cacf06ba373f9b34',1,'h5']]],
  ['h5file_1975',['H5File',['../classh5_1_1H5File.html',1,'h5::H5File&lt; Access_t &gt;'],['../classh5_1_1H5File.html#a63efc51b917cab7fa47a01eac36c43b9',1,'h5::H5File::H5File(std::string file_name, bool append_to_file=false)'],['../classh5_1_1H5File.html#af9dcf4b1ee5cea6b52b93d169a0bbdff',1,'h5::H5File::H5File(const H5File &amp;)=delete']]],
  ['h5file_3c_20h5_3a_3aaccesstype_3a_3areadonly_20_3e_1976',['H5File&lt; h5::AccessType::ReadOnly &gt;',['../classh5_1_1H5File.html',1,'h5']]],
  ['h5file_3c_20h5_3a_3aaccesstype_3a_3areadwrite_20_3e_1977',['H5File&lt; h5::AccessType::ReadWrite &gt;',['../classh5_1_1H5File.html',1,'h5']]],
  ['h5filelock_1978',['H5FileLock',['../structobservers_1_1Tags_1_1H5FileLock.html',1,'observers::Tags']]],
  ['h5interpolator_1979',['H5Interpolator',['../structCce_1_1OptionTags_1_1H5Interpolator.html',1,'Cce::OptionTags']]],
  ['h5isbondidata_1980',['H5IsBondiData',['../structCce_1_1OptionTags_1_1H5IsBondiData.html',1,'Cce::OptionTags']]],
  ['h5lookaheadtimes_1981',['H5LookaheadTimes',['../structCce_1_1OptionTags_1_1H5LookaheadTimes.html',1,'Cce::OptionTags']]],
  ['h5worldtubeboundary_1982',['H5WorldtubeBoundary',['../classCce_1_1H5WorldtubeBoundary.html',1,'Cce']]],
  ['h5worldtubeboundarydatamanager_1983',['H5WorldtubeBoundaryDataManager',['../structCce_1_1Tags_1_1H5WorldtubeBoundaryDataManager.html',1,'Cce::Tags']]],
  ['halfpower_1984',['HalfPower',['../structFilters_1_1Exponential_1_1HalfPower.html',1,'Filters::Exponential']]],
  ['halfspacemirror_1985',['HalfSpaceMirror',['../classElasticity_1_1Solutions_1_1HalfSpaceMirror.html',1,'Elasticity::Solutions']]],
  ['halfwidth_1986',['HalfWidth',['../structBurgers_1_1Solutions_1_1Bump_1_1HalfWidth.html',1,'Burgers::Solutions::Bump']]],
  ['halt_1987',['Halt',['../namespaceParallel.html#af31fff079d116e958890e079a35955cfa4558f7fa8f5356a88a53347ad89babde',1,'Parallel']]],
  ['hamiltonian_1988',['Hamiltonian',['../namespaceXcts.html#afc9a7d41a8c51fdc912cfc3e8196fa78ad8dbcb7f98b38c5c9f9a0ad33e94ec2a',1,'Xcts']]],
  ['hamiltonianandlapse_1989',['HamiltonianAndLapse',['../namespaceXcts.html#afc9a7d41a8c51fdc912cfc3e8196fa78a1d7c1747c46332d5d8dff1ff4c751e09',1,'Xcts']]],
  ['hamiltonianlapseandshift_1990',['HamiltonianLapseAndShift',['../namespaceXcts.html#afc9a7d41a8c51fdc912cfc3e8196fa78a5e29b37ae66a23995a8a1e87e49ea805',1,'Xcts']]],
  ['hard_5flink_5fcount_1991',['hard_link_count',['http://en.cppreference.com/w/cpp/experimental/fs/hard_link_count.html',1,'std::experimental::filesystem::hard_link_count()'],['http://en.cppreference.com/w/cpp/filesystem/hard_link_count.html',1,'std::filesystem::hard_link_count()']]],
  ['hardware_5fconcurrency_1992',['hardware_concurrency',['http://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency.html',1,'std::thread']]],
  ['harmonic_1993',['Harmonic',['../structScalarWave_1_1Solutions_1_1SemidiscretizedDg_1_1Harmonic.html',1,'ScalarWave::Solutions::SemidiscretizedDg']]],
  ['has_5fdestination_1994',['has_destination',['../structbrigand_1_1has__destination.html',1,'brigand']]],
  ['has_5fedge_1995',['has_edge',['../group__UtilitiesGroup.html#ga4cc9e917f4629191b41c8950542aa1a3',1,'brigand']]],
  ['has_5fequivalence_1996',['has_equivalence',['../structtt_1_1has__equivalence.html',1,'tt']]],
  ['has_5fequivalence_5ft_1997',['has_equivalence_t',['../namespacett.html#a16a8b41066b73e3c0de4eeb0c5e87317',1,'tt']]],
  ['has_5fequivalence_5fv_1998',['has_equivalence_v',['../namespacett.html#a748064ad3db0e62508620e3b3913d4c1',1,'tt']]],
  ['has_5fextension_1999',['has_extension',['http://en.cppreference.com/w/cpp/experimental/fs/path/has_path.html',1,'std::experimental::filesystem::path::has_extension()'],['http://en.cppreference.com/w/cpp/filesystem/path/has_path.html',1,'std::filesystem::path::has_extension()']]],
  ['has_5ffilename_2000',['has_filename',['http://en.cppreference.com/w/cpp/experimental/fs/path/has_path.html',1,'std::experimental::filesystem::path::has_filename()'],['http://en.cppreference.com/w/cpp/filesystem/path/has_path.html',1,'std::filesystem::path::has_filename()']]],
  ['has_5finequivalence_2001',['has_inequivalence',['../structtt_1_1has__inequivalence.html',1,'tt']]],
  ['has_5finequivalence_5ft_2002',['has_inequivalence_t',['../namespacett.html#ac28bf0e1a72eb99f6e0f4025435d13cd',1,'tt']]],
  ['has_5finequivalence_5fv_2003',['has_inequivalence_v',['../namespacett.html#a542d7c9729521f7c23cc97f913a19dcb',1,'tt']]],
  ['has_5fparent_5fpath_2004',['has_parent_path',['http://en.cppreference.com/w/cpp/experimental/fs/path/has_path.html',1,'std::experimental::filesystem::path::has_parent_path()'],['http://en.cppreference.com/w/cpp/filesystem/path/has_path.html',1,'std::filesystem::path::has_parent_path()']]],
  ['has_5fpotential_5fsibling_2005',['has_potential_sibling',['../group__ComputationalDomainGroup.html#gaf0e7346e59a71819c08d9efbfcb99ea2',1,'amr']]],
  ['has_5fpreconditioner_2006',['has_preconditioner',['../classLinearSolver_1_1Serial_1_1PreconditionedLinearSolver.html#ac2ee67e50341af306da71e5be772c4a9',1,'LinearSolver::Serial::PreconditionedLinearSolver']]],
  ['has_5fpup_5fmember_2007',['has_pup_member',['../structParallel_1_1has__pup__member.html',1,'Parallel']]],
  ['has_5fpup_5fmember_5ft_2008',['has_pup_member_t',['../namespaceParallel.html#a27907852d1e51848fc42c073f824554c',1,'Parallel']]],
  ['has_5fpup_5fmember_5fv_2009',['has_pup_member_v',['../namespaceParallel.html#ae9bb92f00c4aa3fb15b1888332bc5462',1,'Parallel']]],
  ['has_5freceived_5ffrom_5fall_5fmortars_2010',['has_received_from_all_mortars',['../group__DiscontinuousGalerkinGroup.html#gaee76646149bd85a9808cbd3dc548eb47',1,'dg']]],
  ['has_5fregister_5fwith_5fobserver_2011',['has_register_with_observer',['../structobservers_1_1has__register__with__observer.html',1,'observers']]],
  ['has_5frelative_5fpath_2012',['has_relative_path',['http://en.cppreference.com/w/cpp/experimental/fs/path/has_path.html',1,'std::experimental::filesystem::path::has_relative_path()'],['http://en.cppreference.com/w/cpp/filesystem/path/has_path.html',1,'std::filesystem::path::has_relative_path()']]],
  ['has_5froot_5fdirectory_2013',['has_root_directory',['http://en.cppreference.com/w/cpp/experimental/fs/path/has_path.html',1,'std::experimental::filesystem::path::has_root_directory()'],['http://en.cppreference.com/w/cpp/filesystem/path/has_path.html',1,'std::filesystem::path::has_root_directory()']]],
  ['has_5froot_5fname_2014',['has_root_name',['http://en.cppreference.com/w/cpp/experimental/fs/path/has_path.html',1,'std::experimental::filesystem::path::has_root_name()'],['http://en.cppreference.com/w/cpp/filesystem/path/has_path.html',1,'std::filesystem::path::has_root_name()']]],
  ['has_5froot_5fpath_2015',['has_root_path',['http://en.cppreference.com/w/cpp/experimental/fs/path/has_path.html',1,'std::experimental::filesystem::path::has_root_path()'],['http://en.cppreference.com/w/cpp/filesystem/path/has_path.html',1,'std::filesystem::path::has_root_path()']]],
  ['has_5fsource_2016',['has_source',['../structbrigand_1_1has__source.html',1,'brigand']]],
  ['has_5fsource_5fand_5fdestination_2017',['has_source_and_destination',['../structbrigand_1_1has__source__and__destination.html',1,'brigand']]],
  ['has_5fsource_5fand_5fdestination_3c_20e_3c_20s_2c_20d_2c_20w_20_3e_2c_20s_2c_20d_20_3e_2018',['has_source_and_destination&lt; E&lt; S, D, W &gt;, S, D &gt;',['../structbrigand_1_1has__source__and__destination_3_01E_3_01S_00_01D_00_01W_01_4_00_01S_00_01D_01_4.html',1,'brigand']]],
  ['has_5fstem_2019',['has_stem',['http://en.cppreference.com/w/cpp/experimental/fs/path/has_path.html',1,'std::experimental::filesystem::path::has_stem()'],['http://en.cppreference.com/w/cpp/filesystem/path/has_path.html',1,'std::filesystem::path::has_stem()']]],
  ['has_5funique_5fobject_5frepresentations_2020',['has_unique_object_representations',['http://en.cppreference.com/w/cpp/types/has_unique_object_representations.html',1,'std']]],
  ['has_5fvalue_2021',['has_value',['http://en.cppreference.com/w/cpp/utility/any/has_value.html',1,'std::any::has_value()'],['http://en.cppreference.com/w/cpp/utility/optional/operator_bool.html',1,'std::optional::has_value()']]],
  ['has_5fvirtual_5fdestructor_2022',['has_virtual_destructor',['http://en.cppreference.com/w/cpp/types/has_virtual_destructor.html',1,'std']]],
  ['has_5fvirtual_5fdestructor_5fv_2023',['has_virtual_destructor_v',['http://en.cppreference.com/w/cpp/experimental/type_trait_variable_templates.html',1,'std::experimental']]],
  ['hasconverged_2024',['HasConverged',['../structConvergence_1_1HasConverged.html',1,'Convergence::HasConverged'],['../structConvergence_1_1Tags_1_1HasConverged.html',1,'Convergence::Tags::HasConverged&lt; Label &gt;'],['../structConvergence_1_1HasConverged.html#ad5de8fd0a4dcf031371b45009653eefe',1,'Convergence::HasConverged::HasConverged(const Criteria &amp;criteria, size_t iteration_id, double residual_magnitude, double initial_residual_magnitude) noexcept'],['../structConvergence_1_1HasConverged.html#a5ae3bd7432613bcad17be24b8085ec49',1,'Convergence::HasConverged::HasConverged(size_t num_iterations, size_t iteration_id) noexcept']]],
  ['hash_2025',['hash',['http://en.cppreference.com/w/cpp/utility/hash.html',1,'std::hash'],['http://en.cppreference.com/w/cpp/locale/collate/hash.html',1,'std::collate::hash()'],['http://en.cppreference.com/w/cpp/locale/collate/hash.html',1,'std::collate_byname::hash()'],['http://en.cppreference.com/w/cpp/utility/hash/hash.html',1,'std::hash::hash()'],['../classobservers_1_1ObservationId.html#aa15f4e17f1473c76b8b9d9b7c80a8567',1,'observers::ObservationId::hash()']]],
  ['hash_5fcode_2026',['hash_code',['http://en.cppreference.com/w/cpp/types/type_index/hash_code.html',1,'std::type_index::hash_code()'],['http://en.cppreference.com/w/cpp/types/type_info/hash_code.html',1,'std::type_info::hash_code()']]],
  ['hash_5ffunction_2027',['hash_function',['http://en.cppreference.com/w/cpp/container/unordered_map/hash_function.html',1,'std::pmr::unordered_map::hash_function()'],['http://en.cppreference.com/w/cpp/container/unordered_multimap/hash_function.html',1,'std::pmr::unordered_multimap::hash_function()'],['http://en.cppreference.com/w/cpp/container/unordered_multiset/hash_function.html',1,'std::pmr::unordered_multiset::hash_function()'],['http://en.cppreference.com/w/cpp/container/unordered_set/hash_function.html',1,'std::pmr::unordered_set::hash_function()'],['http://en.cppreference.com/w/cpp/container/unordered_map/hash_function.html',1,'std::unordered_map::hash_function()'],['http://en.cppreference.com/w/cpp/container/unordered_multimap/hash_function.html',1,'std::unordered_multimap::hash_function()'],['http://en.cppreference.com/w/cpp/container/unordered_multiset/hash_function.html',1,'std::unordered_multiset::hash_function()'],['http://en.cppreference.com/w/cpp/container/unordered_set/hash_function.html',1,'std::unordered_set::hash_function()'],['../classFixedHashMap.html#aaec2ecda13d834766cff2154e248d542',1,'FixedHashMap::hash_function()']]],
  ['hdf5_2028',['HDF5',['../group__HDF5Group.html',1,'']]],
  ['header_2029',['Header',['../classh5_1_1Header.html',1,'h5']]],
  ['header_2ehpp_2030',['Header.hpp',['../Header_8hpp.html',1,'']]],
  ['heavyleptonneutrinos_2031',['HeavyLeptonNeutrinos',['../structneutrinos_1_1HeavyLeptonNeutrinos.html',1,'neutrinos']]],
  ['hecto_2032',['hecto',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['height_2033',['Height',['../structBurgers_1_1Solutions_1_1Bump_1_1Height.html',1,'Burgers::Solutions::Bump::Height'],['../structElasticity_1_1Solutions_1_1BentBeam_1_1Height.html',1,'Elasticity::Solutions::BentBeam&lt; Registrars &gt;::Height']]],
  ['heightpartitioning_2034',['HeightPartitioning',['../structdomain_1_1creators_1_1Cylinder_1_1HeightPartitioning.html',1,'domain::creators::Cylinder']]],
  ['help_2035',['help',['../classOptions_1_1Parser.html#af3735d108023441e3b0156c902a5473a',1,'Options::Parser']]],
  ['helpers_2ehpp_2036',['Helpers.hpp',['../Domain_2Amr_2Helpers_8hpp.html',1,'(Global Namespace)'],['../IO_2H5_2Helpers_8hpp.html',1,'(Global Namespace)']]],
  ['high_5fresolution_5fclock_2037',['high_resolution_clock',['http://en.cppreference.com/w/cpp/chrono/high_resolution_clock.html',1,'std::chrono']]],
  ['history_2038',['History',['../classTimeSteppers_1_1History.html',1,'TimeSteppers']]],
  ['history_3c_20gh_5fvariables_2c_20dt_5fgh_5fvariables_20_3e_2039',['History&lt; gh_variables, dt_gh_variables &gt;',['../classTimeSteppers_1_1History.html',1,'TimeSteppers']]],
  ['historyevolvedvariables_2040',['HistoryEvolvedVariables',['../structTags_1_1HistoryEvolvedVariables.html',1,'Tags']]],
  ['historyiterator_2041',['HistoryIterator',['../classTimeSteppers_1_1HistoryIterator.html',1,'TimeSteppers']]],
  ['hll_2042',['Hll',['../classgrmhd_1_1ValenciaDivClean_1_1BoundaryCorrections_1_1Hll.html',1,'grmhd::ValenciaDivClean::BoundaryCorrections::Hll'],['../classNewtonianEuler_1_1BoundaryCorrections_1_1Hll.html',1,'NewtonianEuler::BoundaryCorrections::Hll&lt; Dim &gt;'],['../structdg_1_1NumericalFluxes_1_1Hll.html',1,'dg::NumericalFluxes::Hll&lt; System &gt;'],['../classBurgers_1_1BoundaryCorrections_1_1Hll.html',1,'Burgers::BoundaryCorrections::Hll']]],
  ['hllc_2043',['Hllc',['../classNewtonianEuler_1_1BoundaryCorrections_1_1Hllc.html',1,'NewtonianEuler::BoundaryCorrections::Hllc&lt; Dim &gt;'],['../structNewtonianEuler_1_1NumericalFluxes_1_1Hllc.html',1,'NewtonianEuler::NumericalFluxes::Hllc&lt; Dim, Frame &gt;']]],
  ['holder_2044',['Holder',['../structintrp_1_1Vars_1_1Holder.html',1,'intrp::Vars']]],
  ['holdertag_2045',['HolderTag',['../structintrp_1_1Vars_1_1HolderTag.html',1,'intrp::Vars']]],
  ['horizon_5fricci_5fscalar_2046',['horizon_ricci_scalar',['../group__TestingFrameworkGroup.html#gab6212a4bc03b660f649d3645742908ec',1,'TestHelpers::Kerr::horizon_ricci_scalar(const Scalar&lt; DataType &gt; &amp;horizon_radius, double mass, double dimensionless_spin_z) noexcept'],['../group__TestingFrameworkGroup.html#ga52ce3f988fc45ef28c91b0b742f3c805',1,'TestHelpers::Kerr::horizon_ricci_scalar(const Scalar&lt; DataType &gt; &amp;horizon_radius_with_spin_on_z_axis, const YlmSpherepack &amp;ylm_with_spin_on_z_axis, const YlmSpherepack &amp;ylm, double mass, const std::array&lt; double, 3 &gt; &amp;dimensionless_spin) noexcept']]],
  ['hours_2047',['hours',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono::hours'],['http://en.cppreference.com/w/cpp/chrono/duration/duration.html',1,'std::chrono::hours::hours()']]],
  ['hybrid_2048',['Hybrid',['../group__NumericalAlgorithmsGroup.html#gga2bdd099599c989714bd6497401452624afb1b6e23a3767d2a31ef7899e6dd3f1e',1,'RootFinder']]],
  ['hybrids_2049',['Hybrids',['../group__NumericalAlgorithmsGroup.html#gga2bdd099599c989714bd6497401452624aa3b07eb68ca39eb0b75ca59169f650d7',1,'RootFinder']]],
  ['hydro_2050',['hydro',['../namespacehydro.html',1,'']]],
  ['hypercubeelement_2051',['HypercubeElement',['../structHypercubeElement.html',1,'']]],
  ['hypercubeelementsiterator_2052',['HypercubeElementsIterator',['../structHypercubeElementsIterator.html',1,'']]],
  ['hypot_2053',['Hypot',['../structfuncl_1_1Hypot.html',1,'funcl']]],
  ['solutions_2054',['Solutions',['../namespacehydro_1_1Solutions.html',1,'hydro']]],
  ['tags_2055',['Tags',['../namespacehydro_1_1Tags.html',1,'hydro']]]
];
