var searchData=
[
  ['k_9833',['k',['http://en.cppreference.com/w/cpp/numeric/random/negative_binomial_distribution/params.html',1,'std::negative_binomial_distribution']]],
  ['kappa_5ftimes_5fp_5fover_5frho_5fsquared_5ffrom_5fdensity_9834',['kappa_times_p_over_rho_squared_from_density',['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_011_01_4.html#a818842159c52f5c00f605dd246069d0d',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 1 &gt;::kappa_times_p_over_rho_squared_from_density(const Scalar&lt; double &gt; &amp;) const noexcept=0'],['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_011_01_4.html#aa0e265e9d3118a90ec9033e1bca7f3e0',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 1 &gt;::kappa_times_p_over_rho_squared_from_density(const Scalar&lt; DataVector &gt; &amp;) const noexcept=0']]],
  ['kappa_5ftimes_5fp_5fover_5frho_5fsquared_5ffrom_5fdensity_5fand_5fenergy_9835',['kappa_times_p_over_rho_squared_from_density_and_energy',['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_012_01_4.html#adbb6355adcecb57f0b6730d155ef5fd3',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 2 &gt;::kappa_times_p_over_rho_squared_from_density_and_energy(const Scalar&lt; double &gt; &amp;, const Scalar&lt; double &gt; &amp;) const noexcept=0'],['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_012_01_4.html#a15b27516c915c161dff5bb5880aedbc2',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 2 &gt;::kappa_times_p_over_rho_squared_from_density_and_energy(const Scalar&lt; DataVector &gt; &amp;, const Scalar&lt; DataVector &gt; &amp;) const noexcept=0']]],
  ['kerr_5fhorizon_5fradius_9836',['kerr_horizon_radius',['../namespacegr_1_1Solutions.html#a0f72e166dcce3d42c2f0f02543dd9029',1,'gr::Solutions']]],
  ['kerrhorizonconforming_9837',['KerrHorizonConforming',['../classdomain_1_1CoordinateMaps_1_1KerrHorizonConforming.html#a78a174573f17df2d1d9edcc30947d988',1,'domain::CoordinateMaps::KerrHorizonConforming']]],
  ['key_5fcomp_9838',['key_comp',['http://en.cppreference.com/w/cpp/container/map/key_comp.html',1,'std::map::key_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/key_comp.html',1,'std::multimap::key_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/key_comp.html',1,'std::multiset::key_comp()'],['http://en.cppreference.com/w/cpp/container/map/key_comp.html',1,'std::pmr::map::key_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/key_comp.html',1,'std::pmr::multimap::key_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/key_comp.html',1,'std::pmr::multiset::key_comp()'],['http://en.cppreference.com/w/cpp/container/set/key_comp.html',1,'std::pmr::set::key_comp()'],['http://en.cppreference.com/w/cpp/container/set/key_comp.html',1,'std::set::key_comp()']]],
  ['key_5feq_9839',['key_eq',['http://en.cppreference.com/w/cpp/container/unordered_map/key_eq.html',1,'std::pmr::unordered_map::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multimap/key_eq.html',1,'std::pmr::unordered_multimap::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multiset/key_eq.html',1,'std::pmr::unordered_multiset::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_set/key_eq.html',1,'std::pmr::unordered_set::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_map/key_eq.html',1,'std::unordered_map::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multimap/key_eq.html',1,'std::unordered_multimap::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multiset/key_eq.html',1,'std::unordered_multiset::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_set/key_eq.html',1,'std::unordered_set::key_eq()'],['../classFixedHashMap.html#ae839b3d9b5ab8ec48e8dccc94337b582',1,'FixedHashMap::key_eq()']]],
  ['keys_5fof_9840',['keys_of',['../group__UtilitiesGroup.html#ga495b431a620b10beb24f1afc90b77e20',1,'keys_of(const std::unordered_map&lt; K, V, H &gt; &amp;m):&#160;StdHelpers.hpp'],['../group__UtilitiesGroup.html#gaf707b57628e9425c91d92eb278a52c99',1,'keys_of(const std::map&lt; K, V, C &gt; &amp;m):&#160;StdHelpers.hpp']]],
  ['kinetic_5fenergy_5fdensity_9841',['kinetic_energy_density',['../namespaceNewtonianEuler.html#a180129925bba777d813b28c5c00f5757',1,'NewtonianEuler::kinetic_energy_density(gsl::not_null&lt; Scalar&lt; DataType &gt; * &gt; result, const Scalar&lt; DataType &gt; &amp;mass_density, const tnsr::I&lt; DataType, Dim, Fr &gt; &amp;velocity) noexcept'],['../namespaceNewtonianEuler.html#ac6746041d1fffa96abe34e8f2ae37d77',1,'NewtonianEuler::kinetic_energy_density(const Scalar&lt; DataType &gt; &amp;mass_density, const tnsr::I&lt; DataType, Dim, Fr &gt; &amp;velocity) noexcept']]],
  ['knuth_5fb_9842',['knuth_b',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine/shuffle_order_engine.html',1,'std::knuth_b']]],
  ['kxrcf_5findicator_9843',['kxrcf_indicator',['../group__LimitersGroup.html#ga013a9ed020d3fdaceaaecc2c7a7fb253',1,'NewtonianEuler::Limiters::Tci']]]
];
