# Distributed under the MIT License.
# See LICENSE.txt for details.

import Fluxes
import Sources


def non_flux_terms_dt_tilde_e(
    tilde_e,
    tilde_s,
    tilde_p,
    lapse,
    shift,
    spatial_metric,
    inv_spatial_metric,
    d_lapse,
    d_shift,
    d_spatial_metric,
    extrinsic_curvature,
    emissivity,
    absorption_opacity,
    scattering_opacity,
    tilde_j,
    tilde_h_normal,
    tilde_h_spatial,
    spatial_velocity,
    lorentz,
    sqrt_det_spatial_metric,
):
    return Sources.source_tilde_e(
        tilde_e,
        tilde_s,
        tilde_p,
        lapse,
        d_lapse,
        d_shift,
        d_spatial_metric,
        inv_spatial_metric,
        extrinsic_curvature,
        spatial_metric,
        emissivity,
        absorption_opacity,
        scattering_opacity,
        tilde_j,
        tilde_h_normal,
        tilde_h_spatial,
        spatial_velocity,
        lorentz,
        sqrt_det_spatial_metric,
    )


def non_flux_terms_dt_tilde_s(
    tilde_e,
    tilde_s,
    tilde_p,
    lapse,
    shift,
    spatial_metric,
    inv_spatial_metric,
    d_lapse,
    d_shift,
    d_spatial_metric,
    extrinsic_curvature,
    emissivity,
    absorption_opacity,
    scattering_opacity,
    tilde_j,
    tilde_h_normal,
    tilde_h_spatial,
    spatial_velocity,
    lorentz,
    sqrt_det_spatial_metric,
):
    return Sources.source_tilde_s(
        tilde_e,
        tilde_s,
        tilde_p,
        lapse,
        d_lapse,
        d_shift,
        d_spatial_metric,
        inv_spatial_metric,
        extrinsic_curvature,
        spatial_metric,
        emissivity,
        absorption_opacity,
        scattering_opacity,
        tilde_j,
        tilde_h_normal,
        tilde_h_spatial,
        spatial_velocity,
        lorentz,
        sqrt_det_spatial_metric,
    )


def tilde_e_flux(
    tilde_e,
    tilde_s,
    tilde_p,
    lapse,
    shift,
    spatial_metric,
    inv_spatial_metric,
    d_lapse,
    d_shift,
    d_spatial_metric,
    extrinsic_curvature,
    emissivity,
    absorption_opacity,
    scattering_opacity,
    tilde_j,
    tilde_h_normal,
    tilde_h_spatial,
    spatial_velocity,
    lorentz,
    sqrt_det_spatial_metric,
):
    return Fluxes.tilde_e_flux(
        tilde_e,
        tilde_s,
        tilde_p,
        lapse,
        shift,
        spatial_metric,
        inv_spatial_metric,
    )


def tilde_s_flux(
    tilde_e,
    tilde_s,
    tilde_p,
    lapse,
    shift,
    spatial_metric,
    inv_spatial_metric,
    d_lapse,
    d_shift,
    d_spatial_metric,
    extrinsic_curvature,
    emissivity,
    absorption_opacity,
    scattering_opacity,
    tilde_j,
    tilde_h_normal,
    tilde_h_spatial,
    spatial_velocity,
    lorentz,
    sqrt_det_spatial_metric,
):
    return Fluxes.tilde_s_flux(
        tilde_e,
        tilde_s,
        tilde_p,
        lapse,
        shift,
        spatial_metric,
        inv_spatial_metric,
    )
