// Distributed under the MIT License.
// See LICENSE.txt for details.

#pragma once

#include <array>

/// \file
/// These functions are generated by Mathematica. They compute the terms in the
/// general relativistic self-force equations for a circular orbit in Kerr
/// spacetime. See CircularOrbit.hpp for details.

namespace GrSelfForce::detail {
/// The functions below are used when `PenetratingHorizon` is `False`. They
/// solve the PDEs in $(r_\star, \theta)$ coordinates, with metric components
/// given in Boyer-Lindquist coordinates.
void getAreal(int m, double a, double om, double r, double th,
              std::array<std::array<double, 10>, 10>& Areal);

void getAimag(int m, double a, double om, double r, double th,
              std::array<std::array<double, 10>, 10>& Aimag);

void getBreal(int m, double a, double om, double r, double th,
              std::array<std::array<double, 10>, 10>& Breal);

void getBimag(int m, double a, double om, double r, double th,
              std::array<std::array<double, 10>, 10>& Bimag);

void getCreal(int m, double a, double om, double r, double th,
              std::array<std::array<double, 10>, 10>& Creal);

void getCimag(int m, double a, double om, double r, double th,
              std::array<std::array<double, 10>, 10>& Cimag);

/// The `_vr` functions below are used when `PenetratingHorizon` is `True`.
/// They instead solve the PDEs in $(r, \cos\theta)$ coordinates, with metric
/// components given in ingoing-Eddington-Finkelstein-like coordinates
/// $(v, r, \theta, \phi)$.
void getAreal_vr(int m, double a, double om, double r, double z, double H,
                 double dHdr, std::array<std::array<double, 10>, 10>& Areal);

void getAimag_vr(int m, double a, double om, double r, double z, double H,
                 double dHdr, std::array<std::array<double, 10>, 10>& Aimag);

void getBreal_vr(int m, double a, double om, double r, double z, double H,
                 double dHdr, std::array<std::array<double, 10>, 10>& Breal);

void getBimag_vr(int m, double a, double om, double r, double z, double H,
                 double dHdr, std::array<std::array<double, 10>, 10>& Bimag);

void getCreal_vr(int m, double a, double om, double r, double z, double H,
                 double dHdr, std::array<std::array<double, 10>, 10>& Creal);

void getCimag_vr(int m, double a, double om, double r, double z, double H,
                 double dHdr, std::array<std::array<double, 10>, 10>& Cimag);

}  // namespace GrSelfForce::detail
