// Distributed under the MIT License.
// See LICENSE.txt for details.

#pragma once

#include <array>

/// \file
/// These functions are generated by Mathematica. They transform results from
/// the GrEffectiveSource code into our form of the equations. See
/// CircularOrbit.hpp for details.

namespace GrSelfForce::detail {
/// The functions below are used when `PenetratingHorizon` is `False`. They
/// solve the PDEs in $(r_\star, \theta)$ coordinates, with metric components
/// given in Boyer-Lindquist coordinates.
void convert_effsource_psi(int m, double a, double r, double th,
                           std::array<double, 10>& real_orig,
                           std::array<double, 10>& imag_orig,
                           std::array<double, 10>& real_conv,
                           std::array<double, 10>& imag_conv);

void convert_effsource_Seff(int m, double a, double r, double th,
                            std::array<double, 10>& real_orig,
                            std::array<double, 10>& imag_orig,
                            std::array<double, 10>& real_conv,
                            std::array<double, 10>& imag_conv);

void convert_effsource_dpsidtheta(int m, double a, double r, double th,
                                  std::array<double, 10>& real_orig,
                                  std::array<double, 10>& imag_orig,
                                  std::array<double, 10>& real_orig_dth,
                                  std::array<double, 10>& imag_orig_dth,
                                  std::array<double, 10>& real_conv_dth,
                                  std::array<double, 10>& imag_conv_dth);

void convert_effsource_dpsidrstar(int m, double a, double r, double th,
                                  std::array<double, 10>& real_orig,
                                  std::array<double, 10>& imag_orig,
                                  std::array<double, 10>& real_orig_dr,
                                  std::array<double, 10>& imag_orig_dr,
                                  std::array<double, 10>& real_conv_drs,
                                  std::array<double, 10>& imag_conv_drs);

/// The `_vr` functions below are used when `PenetratingHorizon` is `True`.
/// They instead solve the PDEs in $(r, \cos\theta)$ coordinates, with metric
/// components given in ingoing-Eddington-Finkelstein-like coordinates
/// $(v, r, \theta, \phi)$.
void convert_effsource_psi_vr(int m, double a, double r, double z,
                           std::array<double, 10>& real_orig,
                           std::array<double, 10>& imag_orig,
                           std::array<double, 10>& real_conv,
                           std::array<double, 10>& imag_conv);

void convert_effsource_Seff_vr(int m, double a, double r, double z,
                            std::array<double, 10>& real_orig,
                            std::array<double, 10>& imag_orig,
                            std::array<double, 10>& real_conv,
                            std::array<double, 10>& imag_conv);

void convert_effsource_dpsidz_vr(int m, double a, double r, double z,
                                  std::array<double, 10>& real_orig,
                                  std::array<double, 10>& imag_orig,
                                  std::array<double, 10>& real_orig_dth,
                                  std::array<double, 10>& imag_orig_dth,
                                  std::array<double, 10>& real_conv_dz,
                                  std::array<double, 10>& imag_conv_dz);

void convert_effsource_dpsidr_vr(int m, double a, double r, double z,
                                  std::array<double, 10>& real_orig,
                                  std::array<double, 10>& imag_orig,
                                  std::array<double, 10>& real_orig_dr,
                                  std::array<double, 10>& imag_orig_dr,
                                  std::array<double, 10>& real_conv_dr,
                                  std::array<double, 10>& imag_conv_dr);

}  // namespace GrSelfForce::detail
