#!/usr/bin/env python

# Distributed under the MIT License.
# See LICENSE.txt for details.

"""Check the output of the short binary black hole regression test.

This is the last step of `.cscs-ci/RunBbhRegression.sh`, which the CSCS
continuous integration pipeline runs on the Eiger cluster (see
`docs/DevGuide/CscsCi.md`). The executables already fail on their own when they
crash or blow up, so the purpose of this script is to catch the failure modes
that leave a zero exit code behind, above all an evolution that stopped early.

The thresholds below are regression guards, not statements about physical
accuracy: the test runs at a resolution far below any production simulation.
They are deliberately loose and should be tightened once the test has been
running for a while.
"""

import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import click
import h5py
import numpy as np

from spectre.IO.H5 import available_subfiles, to_dataframe
from spectre.support.Logging import configure_logging

logger = logging.getLogger(__name__)


class CheckFailure(Exception):
    """Raised when a check fails. Collected and reported all at once."""


def read_dat(h5_file_path, subfile_name):
    """Read the '.dat' subfile named 'subfile_name' into a DataFrame

    Columns are named by the subfile's legend. Raises a 'CheckFailure' listing
    all available subfiles if the subfile is not there, since the subfile names
    are generated by the executables and can change.
    """
    h5_file_path = Path(h5_file_path)
    if not h5_file_path.exists():
        raise CheckFailure(f"File '{h5_file_path}' does not exist.")
    with h5py.File(str(h5_file_path), "r") as h5_file:
        subfile = h5_file.get(subfile_name + ".dat")
        if subfile is None:
            available = available_subfiles(h5_file, extension=".dat")
            raise CheckFailure(
                f"There is no subfile '{subfile_name}.dat' in"
                f" '{h5_file_path}'. Available subfiles are:"
                f" {sorted(available)}"
            )
        return to_dataframe(subfile)


def check_initial_data(id_dir, mass_tolerance, spin_tolerance):
    """Check the apparent horizons found in the initial data

    For an equal-mass, non-spinning binary each hole should have a
    Christodoulou mass of 0.5 and no spin.
    """
    horizons_file = Path(id_dir) / "Horizons.h5"
    for label in ["AhA", "AhB"]:
        horizon = read_dat(horizons_file, label)
        mass = horizon["ChristodoulouMass"].iloc[-1]
        spin = horizon["DimensionlessSpinMagnitude"].iloc[-1]
        logger.info(f"{label}: mass = {mass:g}, spin = {spin:g}")
        if abs(mass - 0.5) > mass_tolerance:
            raise CheckFailure(
                f"The Christodoulou mass of {label} is {mass:g}, which"
                " differs from the expected 0.5 by more than"
                f" {mass_tolerance:g}."
            )
        if spin > spin_tolerance:
            raise CheckFailure(
                f"The dimensionless spin of {label} is {spin:g}, which"
                f" exceeds the tolerance {spin_tolerance:g}."
            )


def check_evolution(inspiral_dir, final_time, constraint_threshold):
    """Check that the evolution ran to completion and stayed sane

    Reaching the final time is the most important check: an evolution that
    stops early, e.g. because it ran out of wallclock time, still exits with a
    zero exit code.
    """
    norms = read_dat(Path(inspiral_dir) / "BbhReductions.h5", "Norms")

    last_time = norms["Time"].iloc[-1]
    logger.info(f"The evolution reached t = {last_time:g} M.")
    # A slab can overshoot the completion time slightly, but it must not
    # undershoot it.
    if last_time < final_time:
        raise CheckFailure(
            f"The evolution stopped at t = {last_time:g} M, before the"
            f" requested final time t = {final_time:g} M. It probably ran out"
            " of wallclock time or terminated early."
        )

    if not np.all(np.isfinite(norms.to_numpy())):
        raise CheckFailure(
            "The observed norms contain non-finite values. The columns are:"
            f" {list(norms.columns)}"
        )

    # The constraint is observed under a composed name such as
    # 'L2Norm(PointwiseL2Norm(GaugeConstraint))', so match on a substring.
    gauge_constraint = norms.filter(like="GaugeConstraint")
    if gauge_constraint.empty:
        raise CheckFailure(
            "No gauge constraint column was observed. The columns are:"
            f" {list(norms.columns)}"
        )
    max_gauge_constraint = gauge_constraint.abs().to_numpy().max()
    logger.info(
        f"The maximum gauge constraint norm is {max_gauge_constraint:g}."
    )
    if max_gauge_constraint > constraint_threshold:
        raise CheckFailure(
            f"The gauge constraint norm reached {max_gauge_constraint:g},"
            f" which exceeds the threshold {constraint_threshold:g}."
        )


def check_horizons_found(inspiral_dir, min_num_observations):
    """Check that the apparent horizon finders ran during the evolution"""
    for label in ["ObservationAhA", "ObservationAhB"]:
        observations = read_dat(Path(inspiral_dir) / "BbhReductions.h5", label)
        logger.info(f"Found {len(observations)} observations of {label}.")
        if len(observations) < min_num_observations:
            raise CheckFailure(
                f"Only {len(observations)} observations of {label} were made,"
                f" but at least {min_num_observations} were expected. The"
                " apparent horizon finder or the control system may have"
                " stopped working."
            )


def collect_performance(id_dir, inspiral_dir):
    """Collect performance metrics from the run

    Nothing is asserted here: these numbers exist so that a step-change
    performance regression is visible when comparing one CI run against
    another. They are deliberately normalized, because the amount of work the
    run does is not fixed. Local time stepping and the control systems mean the
    number of slabs needed to reach the final time varies from run to run, so
    raw wall time conflates "the code got slower" with "the run did more work".

    The wall time that SpECTRE records is `sys::wall_time()`, i.e.
    `CkWallTimer()`, which counts from Charm++ startup. Differences between
    observations therefore isolate a phase, and that is how the evolution's
    start-up cost is separated from its stepping cost below. That separation
    matters for a run this short, where reading the initial data is a large
    fraction of the total.
    """
    metrics = {}

    # Initial data: the elliptic solver writes one row per Newton iteration.
    # Iteration count and time per iteration are reported separately, because a
    # change in the former is a solver regression while a change in the latter
    # is a performance regression.
    try:
        residuals = read_dat(
            Path(id_dir) / "BbhReductions.h5", "NewtonRaphsonResiduals"
        )
        wall_time = residuals["Walltime"].iloc[-1]
        iterations = int(residuals["Iteration"].iloc[-1])
        metrics["initial_data"] = {
            "wall_time_s": float(wall_time),
            "newton_iterations": iterations,
            "wall_time_per_iteration_s": (
                float(wall_time / iterations) if iterations > 0 else None
            ),
            "final_residual": float(residuals["Residual"].iloc[-1]),
        }
    except (CheckFailure, KeyError) as error:
        logger.warning(f"No initial-data performance metrics: {error}")

    # Evolution: 'Time' is simulation time in units of the total mass M, and
    # 'Maximum Walltime' is seconds since start-up. The headline number is
    # M/hr, the figure of merit normally used for binary black hole runs.
    try:
        steps = read_dat(Path(inspiral_dir) / "BbhReductions.h5", "TimeSteps")
        sim_time = steps["Time"]
        wall = steps["Maximum Walltime"]
        startup_s = float(wall.iloc[0])
        stepping_s = float(wall.iloc[-1] - wall.iloc[0])
        advanced_m = float(sim_time.iloc[-1] - sim_time.iloc[0])
        metrics["evolution"] = {
            "startup_wall_time_s": startup_s,
            "wall_time_s": stepping_s,
            "simulation_time_m": advanced_m,
            "simulation_time_per_hour": (
                advanced_m / (stepping_s / 3600.0) if stepping_s > 0 else None
            ),
            "num_slabs": len(steps),
            "wall_time_per_slab_s": (
                stepping_s / len(steps) if len(steps) > 0 else None
            ),
            "num_degrees_of_freedom": float(
                steps["Number of degrees of freedom"].iloc[-1]
            ),
        }
    except (CheckFailure, KeyError) as error:
        logger.warning(f"No evolution performance metrics: {error}")

    for phase, values in metrics.items():
        logger.info(f"Performance ({phase}):")
        for key, value in values.items():
            logger.info(
                f"  {key} = {value:g}"
                if isinstance(value, float)
                else f"  {key} = {value}"
            )
    return metrics


def write_metrics(metrics, output_path):
    """Write the metrics to a JSON file for later comparison

    The context is recorded alongside the numbers because they are only
    comparable between runs that used the same resolution and the same number
    of cores.
    """
    record = {
        "schema": 1,
        "recorded_at": datetime.now(timezone.utc).isoformat(),
        "commit": os.environ.get("CI_COMMIT_SHA"),
        "num_procs": os.environ.get("SPECTRE_NUM_PROCS"),
        "final_time": os.environ.get("SPECTRE_FINAL_TIME"),
        "id_refinement": [
            os.environ.get("SPECTRE_ID_L"),
            os.environ.get("SPECTRE_ID_P"),
        ],
        "evolution_refinement": [
            os.environ.get("SPECTRE_EV_L"),
            os.environ.get("SPECTRE_EV_P"),
        ],
        **metrics,
    }
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as open_file:
        json.dump(record, open_file, indent=2, sort_keys=True)
    logger.info(f"Wrote performance metrics to {output_path}.")


@click.command()
@click.option(
    "--id-dir",
    required=True,
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="Directory holding the output of the initial data solve.",
)
@click.option(
    "--inspiral-dir",
    required=True,
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="Directory holding the output of the evolution.",
)
@click.option(
    "--final-time",
    required=True,
    type=float,
    help="Time in units of M that the evolution was supposed to reach.",
)
@click.option(
    "--mass-tolerance",
    default=0.05,
    show_default=True,
    help="Absolute tolerance on the Christodoulou mass of each hole.",
)
@click.option(
    "--spin-tolerance",
    default=0.05,
    show_default=True,
    help="Upper bound on the dimensionless spin of each hole.",
)
@click.option(
    "--constraint-threshold",
    default=1.0,
    show_default=True,
    help="Upper bound on the L2 norm of the gauge constraint.",
)
@click.option(
    "--min-num-observations",
    default=2,
    show_default=True,
    help="Minimum number of apparent horizon observations in the evolution.",
)
@click.option(
    "--metrics-output",
    type=click.Path(dir_okay=False, writable=True, path_type=Path),
    default=None,
    help=(
        "Write performance metrics to this JSON file. Nothing is asserted"
        " about them; they are kept so a step-change performance regression"
        " is visible when comparing runs."
    ),
)
def check_bbh_regression_command(
    id_dir,
    inspiral_dir,
    final_time,
    mass_tolerance,
    spin_tolerance,
    constraint_threshold,
    min_num_observations,
    metrics_output,
):
    """Check the output of the short binary black hole regression test."""
    checks = [
        lambda: check_initial_data(id_dir, mass_tolerance, spin_tolerance),
        lambda: check_evolution(inspiral_dir, final_time, constraint_threshold),
        lambda: check_horizons_found(inspiral_dir, min_num_observations),
    ]
    # Run all checks before reporting, so a single CI run shows every problem
    # rather than only the first one.
    failures = []
    for check in checks:
        try:
            check()
        except CheckFailure as error:
            failures.append(str(error))
        except KeyError as error:
            # An expected column is missing, i.e. an executable changed the
            # legend it observes.
            failures.append(f"Missing expected column {error} in the output.")
    metrics = collect_performance(id_dir, inspiral_dir)
    if metrics_output:
        write_metrics(metrics, metrics_output)
    if failures:
        for failure in failures:
            logger.error(failure)
        sys.exit(
            "The binary black hole regression test failed"
            f" {len(failures)} check(s)."
        )
    logger.info("All checks passed.")


if __name__ == "__main__":
    configure_logging(log_level=logging.INFO)
    # 'configure_logging' only lowers the level of the 'spectre' logger, but
    # this script runs as '__main__', so set its level as well. Otherwise the
    # informational output below would never reach the CI log.
    logger.setLevel(logging.INFO)
    check_bbh_regression_command(help_option_names=["-h", "--help"])
