# Distributed under the MIT License.
# See LICENSE.txt for details.

# Python reference implementation of gr::Solutions::HighSpinKerrPuncture for
# the SpECTRE pypp unit tests: Kerr initial data in the puncture radial
# coordinate of Liu, Etienne & Shapiro, PRD 80, 121503(R) (2009)
# [arXiv:1001.4077] ("LES").
#
# This reference is mathematically INDEPENDENT of the C++ production code, which
# uses simplified axis-regular Cartesian assembly (coefficients c_delta, c_n,
# c_lambda, ... multiplying n_i, lambda_i, mu_i) and a hand-derived Cartesian
# chain rule. This file instead uses the paper's spherical route throughout:
#
#   Primitive tags (lapse, shift, spatial metric, extrinsic curvature,
#   sqrt-det, inverse metric) are assembled from the paper's PAPER-LITERAL
#   spherical components gamma_rr = Sigma (r + r_+/4)^2/(r^3 (r_BL - r_-)),
#   gamma_thth = Sigma, gamma_phph = A sin^2(theta)/Sigma, K_{r phi},
#   K_{theta phi}, the signed Killing lapse (see below), and
#   beta^phi = -2 M a r_BL/A, transformed to Cartesian with the EXPLICIT
#   coordinate Jacobian J^a_i = d(r, theta, phi)/d(x, y, z) built from trig:
#   gamma_ij = J^T diag(g_rr, g_thth, g_phph) J, K_ij = J^T K_sph J, and
#   beta^i = (dx^i/dphi) beta^phi. sqrt-det and inverse are taken numerically
#   from the assembled gamma_ij (np.linalg.det / inv). None of the C++'s
#   simplified Cartesian coefficient formulas appear here.
#
#   The THREE derivative tags (deriv Lapse, deriv Shift, deriv Spatial Metric)
#   are MACHINE-GENERATED by SymPy from the same paper-literal spherical
#   components: the components are differentiated in SPHERICAL coordinates
#   (r, theta) first, then the three-index objects are transformed to Cartesian
#   with the coordinate Jacobians INCLUDING the Jacobian-derivative (dJ) terms.
#
# Both routes are thus independent of the production C++.
#
# The lapse is the SIGNED analytic lapse
# alpha = (r - r_+/4) sqrt((r_BL - r_-) Sigma / (r A)), negative on the inner
# sheet r < r_+/4 and smooth everywhere except the puncture; the paper's
# nonnegative lapse sqrt(Delta Sigma / A) is its absolute value. With the signed
# lapse the representation is exactly stationary on both sheets, so the time
# derivatives of all tags are identically zero.

import numpy as np


# ---------------------------------------------------------------------------
# Shared geometry and Boyer-Lindquist scalars (spherical route)
# ---------------------------------------------------------------------------
def _r_plus_minus(mass, spin):
    disc = np.sqrt(mass * mass - spin * spin)
    return mass + disc, mass - disc  # r_+, r_-


def _bl_scalars(x, mass, spin):
    """Boyer-Lindquist scalars and geometry at a single Cartesian point x."""
    r_plus, r_minus = _r_plus_minus(mass, spin)
    r = np.sqrt(x[0] ** 2 + x[1] ** 2 + x[2] ** 2)
    z = x[2]
    varpi_squared = x[0] ** 2 + x[1] ** 2
    cos_theta_squared = z * z / (r * r)
    sin_theta_squared = varpi_squared / (r * r)
    r_bl = (r + r_plus / 4.0) ** 2 / r
    sigma = r_bl * r_bl + spin * spin * cos_theta_squared
    delta = r_bl * r_bl - 2.0 * mass * r_bl + spin * spin
    A = (
        r_bl * r_bl + spin * spin
    ) ** 2 - delta * spin * spin * sin_theta_squared
    G = (
        3.0 * r_bl**4
        + 2.0 * spin * spin * r_bl * r_bl
        - spin**4
        - spin * spin * (r_bl * r_bl - spin * spin) * sin_theta_squared
    )
    return {
        "r_plus": r_plus,
        "r_minus": r_minus,
        "r": r,
        "z": z,
        "r_bl": r_bl,
        "Sigma": sigma,
        "Delta": delta,
        "A": A,
        "G": G,
    }


# ---------------------------------------------------------------------------
# Coordinate Jacobian of the spherical map (spherical route)
# ---------------------------------------------------------------------------
# xi^a = (r, theta, phi) as functions of Cartesian x^i = (x, y, z):
#   r = |x|,  theta = arccos(z/r),  phi = atan2(y, x).
# The forward Jacobian J^a_i = d xi^a / d x^i is built explicitly with trig
# (test points are always off-axis, so 1/sin(theta) is finite).
# This is the paper's spherical formulation with generic off-axis points --
# deliberately NOT the axis-regular n/lambda/mu building blocks of the C++
# production route.
def _spherical_coords(x):
    r = np.sqrt(x[0] ** 2 + x[1] ** 2 + x[2] ** 2)
    theta = np.arccos(x[2] / r)
    phi = np.arctan2(x[1], x[0])
    return r, theta, phi


def _forward_jacobian(x):
    """J^a_i = d(r, theta, phi)/d(x, y, z), rows a = (r, theta, phi)."""
    r, theta, phi = _spherical_coords(x)
    st, ct = np.sin(theta), np.cos(theta)
    sp_, cp = np.sin(phi), np.cos(phi)
    # d r / d x^i
    dr = np.array([st * cp, st * sp_, ct])
    # d theta / d x^i
    dtheta = np.array([ct * cp / r, ct * sp_ / r, -st / r])
    # d phi / d x^i
    dphi = np.array([-sp_ / (r * st), cp / (r * st), 0.0])
    return np.array([dr, dtheta, dphi])


def _dxdphi(x):
    """Inverse-Jacobian column dx^i/dphi = (-y, x, 0)."""
    return np.array([-x[1], x[0], 0.0])


# ---------------------------------------------------------------------------
# Spherical physical components, literal transcriptions of Liu, Etienne &
# Shapiro, PRD 80, 121503 (2009), Eqs. (13)-(15)
# ---------------------------------------------------------------------------
def _spherical_metric_diag(x, mass, spin):
    """(gamma_rr, gamma_thth, gamma_phph), paper Eq. (13) in LITERAL form."""
    s = _bl_scalars(x, mass, spin)
    r, r_bl, r_minus, r_plus = s["r"], s["r_bl"], s["r_minus"], s["r_plus"]
    sigma, A = s["Sigma"], s["A"]
    _, theta, _ = _spherical_coords(x)
    sin_theta = np.sin(theta)
    # gamma_rr = Sigma (r + r_+/4)^2 / (r^3 (r_BL - r_-))  [Eq. (13), literal]
    g_rr = sigma * (r + r_plus / 4.0) ** 2 / (r**3 * (r_bl - r_minus))
    g_thth = sigma
    g_phph = A * sin_theta**2 / sigma
    return g_rr, g_thth, g_phph


def _spherical_extrinsic(x, mass, spin):
    """Nonzero K_{r phi}, K_{theta phi}; paper Eqs. (14)-(15) literal."""
    s = _bl_scalars(x, mass, spin)
    r, r_bl, r_minus, r_plus = s["r"], s["r_bl"], s["r_minus"], s["r_plus"]
    sigma, A, G = s["Sigma"], s["A"], s["G"]
    _, theta, _ = _spherical_coords(x)
    st, ct = np.sin(theta), np.cos(theta)
    sqrt_A_sigma = np.sqrt(A * sigma)
    # keep the (1 + r_+/(4 r)) factor literal
    K_rph = (
        mass
        * spin
        * st**2
        / (sigma * sqrt_A_sigma)
        * G
        * (1.0 + r_plus / (4.0 * r))
        / np.sqrt(r * (r_bl - r_minus))
    )
    K_thph = (
        -2.0
        * spin**3
        * mass
        * r_bl
        * ct
        * st**3
        / (sigma * sqrt_A_sigma)
        * (r - r_plus / 4.0)
        * np.sqrt((r_bl - r_minus) / r)
    )
    return K_rph, K_thph


# ---------------------------------------------------------------------------
# Primitive tags (spherical components transformed by explicit Jacobians)
# ---------------------------------------------------------------------------
def _spatial_metric(x, mass, spin):
    g_rr, g_thth, g_phph = _spherical_metric_diag(x, mass, spin)
    J = _forward_jacobian(x)  # J^a_i, rows a = (r, theta, phi)
    g_sph = np.diag([g_rr, g_thth, g_phph])
    # gamma_ij = J^a_i J^b_j g_sph_ab  =  J^T g_sph J
    return J.T @ g_sph @ J


def _extrinsic_curvature(x, mass, spin):
    K_rph, K_thph = _spherical_extrinsic(x, mass, spin)
    J = _forward_jacobian(x)
    # spherical K with only (r,phi) and (theta,phi) off-diagonal entries
    K_sph = np.zeros((3, 3))
    K_sph[0, 2] = K_sph[2, 0] = K_rph
    K_sph[1, 2] = K_sph[2, 1] = K_thph
    # K_ij = J^a_i J^b_j K_sph_ab  =  J^T K_sph J
    return J.T @ K_sph @ J


def _shift(x, mass, spin):
    s = _bl_scalars(x, mass, spin)
    beta_up_phi = -2.0 * mass * spin * s["r_bl"] / s["A"]
    # beta^i = (dx^i/dphi) beta^phi
    return _dxdphi(x) * beta_up_phi


def _lapse(x, mass, spin):
    s = _bl_scalars(x, mass, spin)
    r, r_bl = s["r"], s["r_bl"]
    r_plus, r_minus = s["r_plus"], s["r_minus"]
    sigma, A = s["Sigma"], s["A"]
    # The signed Killing lapse alpha = (r - r_+/4) sqrt((r_BL - r_-) Sigma /
    # (r A)): negative on the inner sheet r < r_+/4, smooth everywhere except
    # the puncture. The paper's nonnegative sqrt(Delta Sigma / A) is |alpha|.
    return (r - r_plus / 4.0) * np.sqrt((r_bl - r_minus) * sigma / (r * A))


def _sqrt_det_spatial_metric(x, mass, spin):
    return np.sqrt(np.linalg.det(_spatial_metric(x, mass, spin)))


def _inverse_spatial_metric(x, mass, spin):
    return np.linalg.inv(_spatial_metric(x, mass, spin))


# ###########################################################################
# BEGIN MACHINE-GENERATED BLOCK (do not edit by hand).
#
# The following three functions are generated by SymPy from the paper-literal
# Liu-Etienne-Shapiro spherical components: the components are differentiated
# in spherical coordinates (r, theta) and then Jacobian-transformed to
# Cartesian (including the Jacobian-derivative terms). deriv(Lapse) is
# obtained by differentiating the SIGNED analytic lapse
# alpha = (r - r_+/4) sqrt((r_BL - r_-) Sigma / (r A)) directly in spherical
# coordinates; it is smooth everywhere except the puncture, so the expression
# is valid on both sheets including at the throat.
# The cse temporaries x0, x1, ... are the generator's common-subexpression
# names, not coordinates; the Cartesian coordinates are the arguments x, y, z.
# Arguments a, rp, rm are spin (= chi * mass), r_+ and r_- respectively.
# ###########################################################################


# ==================== deriv(Lapse)  d_k alpha ====================
def _deriv_lapse(x, y, z, M, a, rp, rm):
    x0 = z**2
    x1 = x**2 + x0 + y**2
    x2 = np.sqrt(x1)
    x3 = x2 ** (-1.0)
    x4 = 4 * x2
    x5 = rp + x4
    x6 = x5**2
    x7 = x3 * x6
    x8 = a**2
    x9 = 256 * x8
    x10 = x1 ** (-1.0)
    x11 = x5**4
    x12 = x10 * x11 + x9
    x13 = x12**2
    x14 = x0 * x10 - 1
    x15 = -32 * M * x7 + x12
    x16 = x15 * x9
    x17 = x13 + x14 * x16
    x18 = x17 ** (-1.0)
    x19 = np.sqrt(-x18 * (rm - 1 / 16 * x7))
    x20 = x0 * x8
    x21 = rp - x4
    x22 = np.sqrt((1 / 256) * x11 + x20)
    x23 = x22 ** (-1.0)
    x24 = 64 * x21 * (-256 * x10 * x15 * x18 * x22 + x23)
    x25 = x1 ** (-3 / 4)
    x26 = x22 * x25
    x27 = 128 * x21
    x28 = x5**3
    x29 = 8 * x10
    x30 = x1 ** (-3 / 2)
    x31 = -x29 + x30 * x5
    x32 = (-x13 - x14 * x16) ** (-1.0)
    x33 = 16 * rm - x7
    x34 = x10 * x5
    x35 = x14 * x8
    x36 = (
        (1 / 4)
        * x3
        * (
            x1 ** (1 / 4) * x21 * x23 * x28 * x31
            - x17
            * x26
            * x27
            * x32
            * x5
            * (
                8 * x3
                + 4
                * x32
                * x33
                * (
                    x12 * x31 * x6
                    - 128
                    * x35
                    * (-128 * M * x3 + 16 * M * x34 - x28 * x30 + x29 * x6)
                )
                - x34
            )
            / x33
            + 1024 * x26
            + x22 * x27 / x1 ** (5 / 4)
        )
    )
    x37 = x19 * (x36 + x20 * x24 / x1 ** (7 / 4))
    return np.array([x * x37, x37 * y, x19 * z * (x24 * x25 * x35 + x36)])


# ==================== deriv(Shift)  d_k beta^i ===================
def _deriv_shift(x, y, z, M, a, rp, rm):
    x0 = a**2
    x1 = 256 * x0
    x2 = x**2
    x3 = y**2
    x4 = z**2
    x5 = x2 + x3 + x4
    x6 = x5 ** (-1.0)
    x7 = np.sqrt(x5)
    x8 = rp + 4 * x7
    x9 = x1 + x6 * x8**4
    x10 = x9**2
    x11 = x4 * x6 - 1
    x12 = x8**2
    x13 = x7 ** (-1.0)
    x14 = M * x13
    x15 = -32 * x12 * x14 + x9
    x16 = x1 * x15
    x17 = x10 + x11 * x16
    x18 = 512 * x15
    x19 = x0 * x18 * x4 * x8 / x5**2
    x20 = x19 / x17**2
    x21 = -x11
    x22 = -x10 + x16 * x21
    x23 = x22 ** (-1.0)
    x24 = 8 * x13
    x25 = x6 * x8
    x26 = 8 * x6
    x27 = x5 ** (-3 / 2)
    x28 = -x26 + x27 * x8
    x29 = x0 * x11
    x30 = 2048 * M * x25 + 128 * x12 * x26 - 16384 * x14 - 128 * x27 * x8**3
    x31 = 4 * x12 * x13
    x32 = x23 * (x23 * x31 * (x12 * x28 * x9 - x29 * x30) - x24 + x25)
    x33 = 8192 * a * x14 * x8
    x34 = x33 * y
    x35 = x * x34
    x36 = x22 ** (-2.0)
    x37 = x19 * x36
    x38 = -1 / x22
    x39 = x38 * (x24 - x25 + x31 * x38 * (x0 * x21 * x30 + x12 * x28 * x9))
    x40 = z * (x18 * x25 * x29 * x36 + x39)
    return np.array(
        [
            [x35 * (x20 + x32), x33 * (-x2 * x37 - x2 * x39 + x23 * x8), 0],
            [x33 * (x20 * x3 + x3 * x32 + x8 / x17), -x35 * (x37 + x39), 0],
            [x34 * x40, -x * x33 * x40, 0],
        ]
    )


# ============== deriv(SpatialMetric)  d_k gamma_ij ===============
def _deriv_spatial_metric(x, y, z, M, a, rp, rm):
    x0 = z**2
    x1 = x**2
    x2 = y**2
    x3 = x1 + x2
    x4 = x0 + x3
    x5 = x4 ** (-1.0)
    x6 = x0 * x5
    x7 = x6 - 1
    x8 = -x7
    x9 = x8 ** (-1.0)
    x10 = a**2
    x11 = 256 * x10
    x12 = np.sqrt(x4)
    x13 = rp + 4 * x12
    x14 = x13**4
    x15 = x0 * x11 + x14
    x16 = x15 * x9
    x17 = (1 / 128) * x16
    x18 = x1 * x5
    x19 = x0 * x1
    x20 = x4 ** (-2.0)
    x21 = x20 * x9
    x22 = 3 * x18 + x19 * x21 - 1
    x23 = x4 ** (-4.0)
    x24 = x0 * x23
    x25 = x22 * x24
    x26 = x13**2
    x27 = x12 ** (-1.0)
    x28 = x26 * x27
    x29 = (16 * rm - x28) ** (-1.0)
    x30 = x26 * x29
    x31 = x15 * x30
    x32 = (1 / 128) * x31
    x33 = x4 ** (-7 / 2)
    x34 = x33 * (x18 - 1)
    x35 = x3 ** (-3.0)
    x36 = x2 * x35
    x37 = x11 + x14 * x5
    x38 = x37**2
    x39 = -32 * M * x28 + x37
    x40 = x11 * x7
    x41 = x15 ** (-1.0)
    x42 = x4 * x41
    x43 = x42 * (x38 + x39 * x40)
    x44 = x43 * x7
    x45 = (1 / 64) * x44
    x46 = x7 ** (-1.0)
    x47 = x13**3
    x48 = 8 * x5
    x49 = x4 ** (-3 / 2)
    x50 = x13 * x49
    x51 = -x48 + x50
    x52 = (1 / 128) * x51
    x53 = x47 * x52
    x54 = x33 * x46 * x53
    x55 = x19 * x54
    x56 = x13 * x5
    x57 = x47 * x49
    x58 = -128 * M * x27 + 16 * M * x56 + x26 * x48 - x57
    x59 = x26 * x51
    x60 = x3 ** (-2.0)
    x61 = (1 / 128) * x7
    x62 = x60 * x61
    x63 = x12 * x13 * x41 * x62
    x64 = x63 * (2 * x26 * x37 * x51 - x40 * x58 - x43 * x59)
    x65 = x2 * x64
    x66 = x55 + x65
    x67 = 2 * x10
    x68 = x19 * x67
    x69 = x4 ** (-9 / 2)
    x70 = x30 * x69
    x71 = x68 * x70
    x72 = -x38
    x73 = x39 * x8
    x74 = x11 * x8
    x75 = x42 * (x11 * x73 + x72)
    x76 = x41 * (512 * x10 * x73 + x72 + x74 * x75)
    x77 = (1 / 128) * x6 * x60 * x76
    x78 = x2 * x77
    x79 = x4 ** (-5 / 2)
    x80 = x15 * x79
    x81 = x4 ** (-3.0)
    x82 = x15 * x81
    x83 = (
        (1 / 256)
        * x29
        * x50
        * (
            3 * x13 * x82
            + 2 * x14 * x49 * x51
            + x30 * x80 * (-8 * x27 + x56)
            - 8 * x80
        )
    )
    x84 = x1 * x83
    x85 = x4 ** (-5.0)
    x86 = x67 * z**4
    x87 = x46 * x85 * x86
    x88 = x1 * x87 + x84
    x89 = x71 - x78 + x88
    x90 = (1 / 256) * x16
    x91 = x6 * x9 + 3
    x92 = x85 * x91
    x93 = x19 * x92
    x94 = x1 * x77
    x95 = x1 * x35
    x96 = 2 / x3
    x97 = x1 * x96 - 1
    x98 = (1 / 256) * x60
    x99 = (1 / 256) * x31
    x100 = x69 * x99
    x101 = x1 * x100 + x34 * x99 + x71
    x102 = y * (
        -x1 * x63 * (2 * x26 * x37 * x51 + x58 * x74 + x59 * x75)
        + x101
        - x25 * x90
        + x55
        + x61 * x75 * x95
        + x7 * x75 * x97 * x98
        + x88
        - x90 * x93
        + x94
    )
    x103 = x53 * x79
    x104 = x7 * x9
    x105 = x104 * x6 + 3 * x6 - 1
    x106 = x105 * x23
    x107 = x106 * x90
    x108 = (1 / 256) * x104
    x109 = x108 * x82
    x110 = x23 * x68 + x84
    x111 = z * (x1 * x103 - x1 * x107 + x101 - x109 * x22 + x110)
    x112 = x0 * x2
    x113 = x112 * x92
    x114 = x43 * x62
    x115 = x32 * x69
    x116 = x112 * x54
    x117 = x1 * x64 + x116
    x118 = x115 * x2 + x117
    x119 = x112 * x67 * x70
    x120 = x2 * x83
    x121 = x120 + x2 * x87
    x122 = x119 + x121 - x94
    x123 = x0 * x67
    x124 = x24 * x67
    x125 = x115 + x124 + x83
    x126 = x * y * z
    x127 = x126 * (x103 - x107 - x108 * x15 * x23 * x91 + x123 * x70 + x125)
    x128 = x123 * x7
    x129 = x128 * x81
    x130 = (1 / 128) * x82
    x131 = x0 * x83
    x132 = x131 + x52 * x57 * x7
    x133 = x0 * x115 - x104 * x105 * x130 + x129 + x132 + x70 * x86
    x134 = x2 * x96 - 1
    x135 = x1 * x115 + x66
    x136 = x2 * x5
    x137 = x112 * x21 + 3 * x136 - 1
    x138 = x137 * x24
    x139 = x33 * (x136 - 1)
    x140 = x100 * x2 + x119 + x139 * x99
    x141 = x * (
        -x113 * x90
        + x116
        + x121
        - x134 * x44 * x98
        - x138 * x90
        + x140
        - x36 * x43 * x61
        - x65
        + x78
    )
    x142 = x120 + x124 * x2
    x143 = z * (x103 * x2 - x107 * x2 - x109 * x137 + x140 + x142)
    x144 = x106 * x17
    x145 = x62 * x76
    x146 = x33 * x7
    x147 = x146 * x30 * x67
    x148 = x126 * (x0 * x54 + x125 - x144 + x145 + x147 - x64)
    x149 = x128 * x30 * x33
    x150 = np.sqrt(x8)
    x151 = x150 ** (-1.0)
    x152 = (
        x0 * x100
        + x0 * x103
        - x105 * x109
        + x129
        + x131
        + x146 * x99
        + x149
        - 1 / 256 * x15 * x151 * x24 * (x150 + 3 * x151 * x7)
    )
    x153 = x * x152
    x154 = x152 * y
    x155 = x7**2
    return np.array(
        [
            [
                [
                    x * (-x17 * x25 + x32 * x34 + x36 * x45 + x66 + x89),
                    x102,
                    x111,
                ],
                [x102, x * (-x113 * x17 + x114 * x97 + x118 + x122), x127],
                [x111, x127, x * x133],
            ],
            [
                [y * (x114 * x134 + x135 - x17 * x93 + x89), x141, x127],
                [
                    x141,
                    y * (x117 + x122 - x138 * x17 + x139 * x32 + x45 * x95),
                    x143,
                ],
                [x127, x143, x133 * y],
            ],
            [
                [
                    z * (-x1 * x144 + x1 * x147 + x110 + x135 - x145 * x2),
                    x148,
                    x153,
                ],
                [
                    x148,
                    z * (-x1 * x145 + x118 + x142 - x144 * x2 + x147 * x2),
                    x154,
                ],
                [
                    x153,
                    x154,
                    z
                    * (
                        -x130 * x155 * x9 * (x104 + 3)
                        + x132
                        + x146 * x32
                        + x149
                        + x155 * x20 * x67
                    ),
                ],
            ],
        ]
    )


# END MACHINE-GENERATED BLOCK.
# ###########################################################################


def _deriv_lapse_tag(x, mass, spin):
    r_plus, r_minus = _r_plus_minus(mass, spin)
    return _deriv_lapse(x[0], x[1], x[2], mass, spin, r_plus, r_minus)


def _deriv_shift_tag(x, mass, spin):
    r_plus, r_minus = _r_plus_minus(mass, spin)
    return _deriv_shift(x[0], x[1], x[2], mass, spin, r_plus, r_minus)


def _deriv_spatial_metric_tag(x, mass, spin):
    r_plus, r_minus = _r_plus_minus(mass, spin)
    return _deriv_spatial_metric(x[0], x[1], x[2], mass, spin, r_plus, r_minus)


# ---------------------------------------------------------------------------
# pypp entry point. Tag order matches HighSpinKerrPuncture::tags exactly.
# ---------------------------------------------------------------------------
def high_spin_kerr_puncture_variables(x, t, mass, dimensionless_spin):
    spin = dimensionless_spin * mass  # a = chi * M
    return {
        "Lapse": _lapse(x, mass, spin),
        "dt(Lapse)": 0.0,
        "deriv(Lapse)": _deriv_lapse_tag(x, mass, spin),
        "Shift": _shift(x, mass, spin),
        "dt(Shift)": np.zeros(3),
        "deriv(Shift)": _deriv_shift_tag(x, mass, spin),
        "SpatialMetric": _spatial_metric(x, mass, spin),
        "dt(SpatialMetric)": np.zeros((3, 3)),
        "deriv(SpatialMetric)": _deriv_spatial_metric_tag(x, mass, spin),
        "SqrtDetSpatialMetric": _sqrt_det_spatial_metric(x, mass, spin),
        "ExtrinsicCurvature": _extrinsic_curvature(x, mass, spin),
        "InverseSpatialMetric": _inverse_spatial_metric(x, mass, spin),
    }
