# Distributed under the MIT License.
# See LICENSE.txt for details.

option(SPECTRE_USE_ALWAYS_INLINE "Force SpECTRE inlining." ON)

set(_SPECTRE_USE_ALWAYS_INLINE 0)

if(SPECTRE_USE_ALWAYS_INLINE)
  set(_SPECTRE_USE_ALWAYS_INLINE 1)
endif()

set_property(
  TARGET SpectreFlags
  APPEND PROPERTY
  INTERFACE_COMPILE_DEFINITIONS
  $<$<COMPILE_LANGUAGE:CXX>:SPECTRE_USE_ALWAYS_INLINE=${_SPECTRE_USE_ALWAYS_INLINE}>
)
