# Distributed under the MIT License.
# See LICENSE.txt for details.

# Lint with clang-tidy. We check only code that changed relative to the
# nearest common ancestor commit with `sxs-collaboration/spectre/develop`.
name: Clang-tidy

on: workflow_call

jobs:
  clang_tidy:
    name: Clang-tidy
    if: >
      (github.event_name == 'pull_request'
       && github.repository == 'sxs-collaboration/spectre'
       && github.base_ref == 'develop')
      || github.ref != 'refs/heads/develop'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container || 'sxscollaboration/spectre:dev' }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      # Work around https://github.com/actions/checkout/issues/760
      - name: Trust checkout
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
      # Some cpp20 features aren't supported until clang-tidy-16. See:
      # https://stackoverflow.com/questions/46114214/lambda-implicit-capture-fails-with-variable-declared-from-structured-binding#comment135007519_46115028
      # The clang-tidy-diff tool doesn't report exit codes until version
      # 18.1.0, so we grab the version that does:
      # https://github.com/llvm/llvm-project/commit/4294bca5e4f6e6e8cfdbd9fbe8751c5e5415fd47
      - name: Install clang-tidy-16
        run: |
          apt-get update -y
          apt-get remove -y clang-tidy clang-tidy-14
          apt-get install -y clang-tidy-16
          ln -s /usr/bin/clang-tidy-16 /usr/bin/clang-tidy
          wget https://raw.githubusercontent.com/llvm/llvm-project/4294bca5e4f6e6e8cfdbd9fbe8751c5e5415fd47/clang-tools-extra/clang-tidy/tool/clang-tidy-diff.py
          chmod +x clang-tidy-diff.py
          mv clang-tidy-diff.py /usr/bin/clang-tidy-diff.py
          ln -s /usr/bin/clang-tidy-diff.py /usr/bin/clang-tidy-diff
      - name: Configure annotations
        # Has to be accessible outside the container, see issue:
        # https://github.com/actions/toolkit/issues/305
        run: |
          cp .github/problem_matchers/ClangTidy.json "$HOME/"
          echo "::add-matcher::$HOME/ClangTidy.json"
      - name: Fetch sxs-collaboration/spectre/develop
        run: >
          cd $GITHUB_WORKSPACE

          git remote add upstream
          https://github.com/sxs-collaboration/spectre.git

          git remote -v

          git fetch upstream develop
      - name: Configure with cmake
        run: >
          mkdir build && cd build

          cmake
          -D CMAKE_C_COMPILER=clang-14
          -D CMAKE_CXX_COMPILER=clang++-14
          -D CMAKE_Fortran_COMPILER=gfortran
          -D CHARM_ROOT=${CHARM_ROOT}
          -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -D OVERRIDE_ARCH=x86-64
          -D USE_CCACHE=OFF
          -D USE_PCH=OFF
          -D DEBUG_SYMBOLS=OFF
          -D BUILD_PYTHON_BINDINGS=ON
          -D SPECTRE_AUTODIFF=ON
          -D SPECTRE_FETCH_MISSING_DEPS=ON
          $GITHUB_WORKSPACE

          make -j4 module_All Libsharp-external
      - name: Check clang-tidy
        run: >
          UPSTREAM_HASH=$(git merge-base HEAD upstream/develop)

          echo "Running clang-tidy relative to: $UPSTREAM_HASH\n"

          git diff -U0 $UPSTREAM_HASH |
            clang-tidy-diff -path build -p1 -use-color -j1 \
            -extra-arg=-I/usr/include/hdf5/serial \
            -extra-arg=-I$GITHUB_WORKSPACE/build/_deps/autodiff-src
